services:
  soga:
    image: ${SOGA_DOCKER_IMAGE:-ghcr.io/xdaidai666/soga:2.13.7}
    container_name: soga
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ../data:/etc/soga
